version: '3.1'

services:
  app:
    container_name: campusfire-app
    image: campusfire-app
    ports:
      - '4001:4001'
  mongodb:
    container_name: campusfire-database
    image: 'bitnami/mongodb:4.4'
    ports:
      - '27017:27017'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=replicaset
      - MONGODB_EXTRA_FLAGS=--bind_ip_all
