import { gql } from 'apollo-server-express';

const typeDefs = gql`
  enum Gender {
    MALE
    FEMALE
    OTHER
  }

  enum Faculty {
    FACULTY_OF_ARTS
    CUMMING_SCHOOL_OF_MEDICINE
    SCHOOL_OF_ARCHITECTURE_PLANNING_AND_LANDSCAPE
    HASKAYNE_SCHOOL_OF_BUSINESS
    FACULTY_OF_KINESIOLOGY
    FACULTY_OF_LAW
    FACULTY_OF_NURSING
    SCHULICH_SCHOOL_OF_ENGINEERING
    FACULTY_OF_SCIENCE
    FACULTY_OF_SOCIAL_WORK
    FACULTY_OF_VETERINARY_MEDICINE
    WERKLUND_SCHOOL_OF_EDUCATION
  }

  enum Interest {
    TRAVELLING
    EXERCISE
    GYM
    SPORTS
    RUNNING
    FOOTBALL
    HOCKEY
    SOCCER
    THEATRE
    NETFLIX
    MOVIES
    DANCING
    COOKING
    OUTDOORS
    HIKING
    TREKKING
    SKIING
    POLITICS
    PETS
    PHOTOGRAPHY
    ART
    MUSIC
    RAP
    ROCK
    POP
    INDI
    GARDENING
    STUDYING
    CODING
  }
`;

export { typeDefs };
